2019-11-01 23:16:33,943	INFO	main1	<module>	Line:11	app started
2019-11-01 23:16:33,956	WARNING	_internal	_log	Line:122	 * Debugger is active!
2019-11-01 23:16:33,987	INFO	_internal	_log	Line:122	 * Debugger PIN: 185-856-785
2019-11-01 23:16:34,038	INFO	_internal	_log	Line:122	 * Running on http://192.168.2.210:9100/ (Press CTRL+C to quit)
2019-11-01 23:16:37,574	INFO	_internal	_log	Line:122	192.168.2.210 - - [01/Nov/2019 23:16:37] "GET /ProblemSet/init/d362b660-5863-47a5-8f32-15d92dc194a7/ww HTTP/1.1" 200 -
2019-11-01 23:16:37,613	INFO	_internal	_log	Line:122	192.168.2.210 - - [01/Nov/2019 23:16:37] "GET /ProblemSet/answer/d362b660-5863-47a5-8f32-15d92dc194a7/4 HTTP/1.1" 200 -
2019-11-01 23:17:08,649	INFO	_internal	_log	Line:122	192.168.2.210 - - [01/Nov/2019 23:17:08] "GET /ProblemSet/answer/d362b660-5863-47a5-8f32-15d92dc194a7/2 HTTP/1.1" 200 -
2019-11-01 23:17:39,681	INFO	_internal	_log	Line:122	192.168.2.210 - - [01/Nov/2019 23:17:39] "GET /ProblemSet/answer/d362b660-5863-47a5-8f32-15d92dc194a7/2 HTTP/1.1" 200 -
2019-11-01 23:18:10,721	INFO	_internal	_log	Line:122	192.168.2.210 - - [01/Nov/2019 23:18:10] "GET /ProblemSet/answer/d362b660-5863-47a5-8f32-15d92dc194a7/2 HTTP/1.1" 200 -
2019-11-01 23:18:36,942	INFO	_internal	_log	Line:122	 * Detected change in 'C:\\development\\examsystem\\services\\daos\\problemsetDAO.py', reloading
